### ISSUE TITLE
Problem with evaluate part on the colab notebook

### ISSUE THREAD

**Issue by haythemtellili** [husseinmozannar/SOQAL#12]
I am not able to get prediction.json file ! please any help will be appreciated

**Comment by husseinmozannar** [comment]
Will look at this soon, I might be releasing a new colab that fixes all the issues and makes it easier.

**Comment by husseinmozannar** [comment]
I made some changes to the evaluation script, it should have been able to run smoothly before although, try running the updated Colab now and let me know exactly what is happening.

**Comment by haythemtellili** [comment]
Yes it worked thank u but why the f1,em are very low !

**Comment by husseinmozannar** [comment]
For how long did you train (the number in "arabic_squad_train/model.ckpt-XXXX")? and what results are you getting? Ballpark values of F1 should be around 50, check the paper https://arxiv.org/pdf/1906.05394.pdf for full result breakdowns. Some recent work have been able to do better and get up to 70 F1 but not sure if their code is yet available.

**Comment by haythemtellili** [comment]
I just used your colab notebook, i think you have been using the pertained Bert multilingual model , so  where can i find arabic_squad_train checkpoint and have i retrain the model ?

**Comment by husseinmozannar** [comment]
If you follow the notebook exactly, this is what you should get (gpu instance on Colab takes maybe 1-2hours):
{"exact_match": 20.21505376344086, "f1": 52.098255315053166, "exact_sentence": 91.11111111111111}

Now to improve on this, one can train on training set of ARCD for one more epoch for example, or use Arabic trained Bert.

**Comment by husseinmozannar** [comment]
There is also an available to download [trained Bert model ](https://storage.googleapis.com/soqal_traind_models/mod.zip). This is linked on the main readme page.

**Comment by haythemtellili** [comment]
Thank you but i don't know why when i try to run your colab, it ran just for 5 min and then i get too low result (6 as f1 score) !

**Comment by husseinmozannar** [comment]
Please make sure to have the Colab run with a  GPU and make sure the training epochs is set  tot 2

**Comment by husseinmozannar** [comment]
Closing this issue for now, GPU required to run the colab and results are consistent.
