### ISSUE TITLE
evaluate.py script isn't removing the right articles set 

### ISSUE THREAD

**Issue by ahmednasserswe** [husseinmozannar/SOQAL#7]
Hey there!

In the `evaluate.py` 
The script is removing the following set of articles (quoted from the code)
```    
def remove_articles(text):
        return re.sub(r'\b(a|an|the)\b', ' ', text)
```

However, you should remove "ال" instead 

You could use the evaluation script from MLQA instead https://github.com/facebookresearch/MLQA/blob/master/mlqa_evaluation_v1.py

Could you please confirm that the results showed in the paper is evaluated using this script? because this issue affects the results and I am comparing my results to yours.

Let me know if you want me to contribute to that!

Thanks!

**Comment by husseinmozannar** [comment]
That is a great catch, I must have forgotten to update the normalize_answer routine, to clean/normalize Arabic text you can use the clean_str routine found in embedding/aravec_embedding.py, I think this has to be also applied to the paragraphs but I am not sure.

I think the evaluate.py script is what was used in the paper, however I agree we should be removing lam el ta3rif as was done in the MLQA script in combination with the other fixes in the clean_str routine, feel free to report results according to this script and the fixed one.

**Comment by ahmednasserswe** [comment]
Thanks for your response!

I can do that next week and comment with the results. Could you confirm that you have used this set of hyperparam like in the colab and that you used `multi_cased_L-12_H-768_A-12` not the uncased multilingual model recommended by google? https://colab.research.google.com/drive/19a_jIKpjhQez0KTa_Qwh2BW2nryGXzhb

Thanks!

**Comment by husseinmozannar** [comment]
The results are with the multi_cased model multi_cased_L-12_H-768_A-12 which is recommended by google, the uncased model is the one **not** recommended but it fits on smaller GPUs.

**Comment by ahmednasserswe** [comment]
If you could, it would be easier if you send me the generated predictions files. thanks

**Comment by husseinmozannar** [comment]
added the removed_articles script from MLQA to evaluate.py, I currently don't have the prediction files
